// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.EmpMapModel;

namespace WebAPI.Migrations.EmployeeMapDetail
{
    [DbContext(typeof(EmployeeMapDetailContext))]
    [Migration("20200410100330_EmpMap")]
    partial class EmpMap
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.EmpMapModel.EmployeeMapDetail", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LevEnddt")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LevStartdt")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Levid")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("empid")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("eid");

                    b.ToTable("employeeMapDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
